### ISSUE TITLE
Could not get channel for player when joining

### ISSUE THREAD

**Issue by TypicalFin** [ThomasOM/Pledge#13]
Happens quite often if you try to login with very high ping.

`Caused by: java.lang.NoSuchFieldException: Could not find field in class net.minecraft.server.v1_8_R3.PacketStatusListener with names [EntityPlayer]`

I've had the same error happen to me with `PacketHandshakeListener` instead.
Using ViaVersion 4.9.2 (joining on native server version, though) and ProtocolLib 5.1.0

```
[17:40:37 ERROR]: Could not pass event PlayerLoginEvent to Anticheat v1.0-SNAPSHOT
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PlayerList.attemptLogin(PlayerList.java:472) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:118) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:875) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
Caused by: java.lang.RuntimeException: Could not get channel for player: TypicalFin
        at me.typicalfin.anticheat.shaded.pledge.channel.ReflectiveChannelAccess.getChannel(ReflectiveChannelAccess.java:68) ~[?:?]
        at me.typicalfin.anticheat.shaded.pledge.PledgeImpl.onPlayerLogin(PledgeImpl.java:218) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_231]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        ... 14 more
Caused by: java.lang.NoSuchFieldException: Could not find field in class net.minecraft.server.v1_8_R3.PacketStatusListener with names [EntityPlayer]
        at me.typicalfin.anticheat.shaded.pledge.util.ReflectionUtil.getFieldByClassNames(ReflectionUtil.java:21) ~[?:?]        at me.typicalfin.anticheat.shaded.pledge.channel.ReflectiveChannelAccess.getChannel(ReflectiveChannelAccess.java:57) ~[?:?]
        at me.typicalfin.anticheat.shaded.pledge.PledgeImpl.onPlayerLogin(PledgeImpl.java:218) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_231]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        ... 14 more```

**Comment by TypicalFin** [comment]
Seems to be related to https://github.com/ThomasOM/Pledge/issues/7#issuecomment-1518382026

**Comment by TypicalFin** [comment]
It would also be a good idea to implement some kind of a failsafe if an error occurs whilst creating a handler. Perhaps, kick the player?

**Comment by TypicalFin** [comment]
Fixed with latest PR
